### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bwmorales** [plijnzaad/quilt#2]
@plijnzaad, I'm wondering if there's a license for this software, specifically to determine if it's okay to use this in a commercial context.

Thanks!

**Comment by plijnzaad** [comment]
Hi Benjamin,

veel free to use and even charge for it, provided you won't claim it is
your own :-) Also, please don't hold me liable for any damages that may
result from using the software, it comes with no guarantees of course.

If this is not enough, let me think about it and I will put the appropriate
open source licences in the repo, may take some time though.

Cheers,

Philip

Op wo 9 mrt. 2022 om 21:32 schreef Benjamin Morales <
***@***.***>:

**Comment by bwmorales** [comment]
Thanks for the quick reply, Philip—I'll bring this back to the team for review. Much appreciated!
